### ISSUE TITLE
Username field need to be required 

### ISSUE THREAD

**Issue by nmanikumar5** [shaikhussian/react-native-loginmodule-Example#1]
Please find the screenshot 
I just tried to submit the form without entering the fields after the first login and logout.
Procedure to find the issue:

* Entered the Username and Password and logged in 
* Do logout 
* Now, again try to login without entering the username and password 

 Code:

            <Form>
              <UserName />
              <Password />
            </Form>

    let AppName = 'AppName'; // Name of the app
    const url = "URL" //Api url
    const fields = {
      UserName: 'UserName',
      Password: 'Password',
    };
    const headers = {
      'Content-Type': 'application/json',
      // Authorization: 'bearer {{"Token"}}',
    };
    //pass the key like 'Login' for login and 'register' for register
    const parameters = {
      AppName: AppName,
      url: url,
      headers: headers,
      fields: fields,
      field: 'Login',
    };
    ButtonAction (parameters).then (res => {
      if (res != undefined) {
        // alert (JSON.stringify (res));
        if (res.isvalid != undefined) {
          console.log ('res');
          //this is for handling validation alerts
        } else {
          // alert ('RES ID: ' + res.id);
          AsyncStorage.setItem ('userid', res.id);
          this.props.navigation.navigate ('Dashboard');
        }
      }
    });

![screen shot 2018-08-28 at 12 49 27 pm](https://user-images.githubusercontent.com/25512433/44706938-d5127700-aac0-11e8-9d2a-af9b17fe24dc.png)

**Comment by shaikhussian** [comment]
@nmanikumar5  it got fixed with latest version :1.1.7
