### ISSUE TITLE
Custom Styles not working properly 

### ISSUE THREAD

**Issue by nmanikumar5** [shaikhussian/react-native-loginmodule-Example#2]
Code:

            <Form>
              <FirstName
                placeholder="Username"
                style={{backgroundColor: 'red'}}
              />
              <LastName />
              <UserName />
              <EMail />
              <PhoneNumber />
              <Password />
            </Form>

Placeholder disappeared when I added the custom style to username field

![screen shot 2018-08-28 at 12 34 48 pm](https://user-images.githubusercontent.com/25512433/44707602-8fef4480-aac2-11e8-98c9-e55509f92eb3.png)

**Comment by shaikhussian** [comment]
@nmanikumar5 once check the native base styles

in this module i used native base input fields
